### ISSUE TITLE
Exceptions should be thrown for the upper level to handle.

### ISSUE THREAD

**Issue by neilACC** [benhoyt/graphyte#10]
https://github.com/Jetsetter/graphyte/blob/200781c5105140df32b8e18bbec497cc0be5d40e/graphyte.py#L130-L133

**Comment by benhoyt** [comment]
Hi @thinkinside-LQ, this is actually intentional default behavior for `graphyte`. The rationale is that generally you want the sends to happen on a background thread (`interval` not None) and the best you can do is have the background thread log the errors. And if you do want graphyte to send on the current thread (`interval=None`), the thinking is that logging an error is a reasonable default when an error occurs sending a metric.

However, per the README, you can customize logging and error handling by subclassing `Sender` and overriding `send_message` or `send_socket`. For example:

```python
class MySender(graphyte.Sender):
    def send_socket(self, message):
        try:
            self.send_message(message)
        except OSError as error:
            print('Socket/send error:', error)
        except Exception as error:
            print('Another error occurred:', error)
 ```
